import '../enums.dart';
import '../models.dart';

/// URL keyboard - primary layout with common URL characters accessible.
/// Has .com, /, : readily available on the bottom row.
final KeyboardLayout urlLayoutPrimary = [
  [
    VirtualKey.character(text: 'q'),
    VirtualKey.character(text: 'w'),
    VirtualKey.character(text: 'e'),
    VirtualKey.character(text: 'r'),
    VirtualKey.character(text: 't'),
    VirtualKey.character(text: 'y'),
    VirtualKey.character(text: 'u'),
    VirtualKey.character(text: 'i'),
    VirtualKey.character(text: 'o'),
    VirtualKey.character(text: 'p'),
  ],
  [
    VirtualKey.character(text: 'a'),
    VirtualKey.character(text: 's'),
    VirtualKey.character(text: 'd'),
    VirtualKey.character(text: 'f'),
    VirtualKey.character(text: 'g'),
    VirtualKey.character(text: 'h'),
    VirtualKey.character(text: 'j'),
    VirtualKey.character(text: 'k'),
    VirtualKey.character(text: 'l'),
  ],
  [
    VirtualKey.action(action: KeyAction.shift, flex: 1),
    VirtualKey.character(text: 'z'),
    VirtualKey.character(text: 'x'),
    VirtualKey.character(text: 'c'),
    VirtualKey.character(text: 'v'),
    VirtualKey.character(text: 'b'),
    VirtualKey.character(text: 'n'),
    VirtualKey.character(text: 'm'),
    VirtualKey.action(action: KeyAction.backSpace, flex: 1),
  ],
  [
    VirtualKey.action(action: KeyAction.symbols, flex: 1),
    VirtualKey.character(text: '/'),
    VirtualKey.character(text: '.'),
    VirtualKey.action(action: KeyAction.space, flex: 2),
    VirtualKey.character(text: '-'),
    VirtualKey.character(text: ':', capsText: ':'),
    VirtualKey.action(action: KeyAction.go, flex: 1),
  ],
];

/// URL keyboard - secondary layout (numbers & symbols).
final KeyboardLayout urlLayoutSecondary = [
  [
    VirtualKey.character(text: '1'),
    VirtualKey.character(text: '2'),
    VirtualKey.character(text: '3'),
    VirtualKey.character(text: '4'),
    VirtualKey.character(text: '5'),
    VirtualKey.character(text: '6'),
    VirtualKey.character(text: '7'),
    VirtualKey.character(text: '8'),
    VirtualKey.character(text: '9'),
    VirtualKey.character(text: '0'),
  ],
  [
    VirtualKey.character(text: '-'),
    VirtualKey.character(text: '_'),
    VirtualKey.character(text: '.'),
    VirtualKey.character(text: '/'),
    VirtualKey.character(text: ':'),
    VirtualKey.character(text: '?'),
    VirtualKey.character(text: '='),
    VirtualKey.character(text: '&'),
    VirtualKey.character(text: '#'),
    VirtualKey.character(text: '%'),
  ],
  [
    VirtualKey.action(action: KeyAction.symbolsAlt, flex: 1),
    VirtualKey.character(text: '@'),
    VirtualKey.character(text: '+'),
    VirtualKey.character(text: '~'),
    VirtualKey.character(text: '!'),
    VirtualKey.character(text: '*'),
    VirtualKey.character(text: "'"),
    VirtualKey.character(text: '"'),
    VirtualKey.action(action: KeyAction.backSpace, flex: 1),
  ],
  [
    VirtualKey.action(action: KeyAction.symbols, flex: 1),
    VirtualKey.character(text: '/'),
    VirtualKey.character(text: '.'),
    VirtualKey.action(action: KeyAction.space, flex: 2),
    VirtualKey.character(text: '-'),
    VirtualKey.character(text: ':'),
    VirtualKey.action(action: KeyAction.go, flex: 1),
  ],
];

/// URL keyboard - tertiary layout (more symbols).
final KeyboardLayout urlLayoutTertiary = [
  [
    VirtualKey.character(text: '['),
    VirtualKey.character(text: ']'),
    VirtualKey.character(text: '{'),
    VirtualKey.character(text: '}'),
    VirtualKey.character(text: '<'),
    VirtualKey.character(text: '>'),
    VirtualKey.character(text: '^'),
    VirtualKey.character(text: '|'),
    VirtualKey.character(text: '\\'),
    VirtualKey.character(text: '`'),
  ],
  [
    VirtualKey.character(text: '€'),
    VirtualKey.character(text: '£'),
    VirtualKey.character(text: '¥'),
    VirtualKey.character(text: '\$'),
    VirtualKey.character(text: '©'),
    VirtualKey.character(text: '®'),
    VirtualKey.character(text: '™'),
    VirtualKey.character(text: '°'),
    VirtualKey.character(text: '•'),
    VirtualKey.character(text: '…'),
  ],
  [
    VirtualKey.action(action: KeyAction.symbolsAlt, flex: 1),
    VirtualKey.character(text: '@'),
    VirtualKey.character(text: '+'),
    VirtualKey.character(text: '~'),
    VirtualKey.character(text: '!'),
    VirtualKey.character(text: '*'),
    VirtualKey.character(text: "'"),
    VirtualKey.character(text: '"'),
    VirtualKey.action(action: KeyAction.backSpace, flex: 1),
  ],
  [
    VirtualKey.action(action: KeyAction.symbols, flex: 1),
    VirtualKey.character(text: '/'),
    VirtualKey.character(text: '.'),
    VirtualKey.action(action: KeyAction.space, flex: 2),
    VirtualKey.character(text: '-'),
    VirtualKey.character(text: ':'),
    VirtualKey.action(action: KeyAction.go, flex: 1),
  ],
];
